# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Log.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 389)
        self.frame_92 = QtWidgets.QFrame(Form)
        self.frame_92.setGeometry(QtCore.QRect(170, 70, 231, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_92.sizePolicy().hasHeightForWidth())
        self.frame_92.setSizePolicy(sizePolicy)
        self.frame_92.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_92.setStyleSheet("#frame_92{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.25, x2:1, y2:0.886364, stop:0.0681818 rgba(0, 196, 211, 255), stop:1 rgba(234, 125, 255, 255));\n"
"border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    font: 16pt \"幼圆\";\n"
"    color:rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"    padding-left:5px;\n"
"}")
        self.frame_92.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_92.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_92.setObjectName("frame_92")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_92)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_99 = QtWidgets.QLabel(self.frame_92)
        self.label_99.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 11pt \"幼圆\";")
        self.label_99.setObjectName("label_99")
        self.verticalLayout.addWidget(self.label_99)
        self.frame_90 = QtWidgets.QFrame(self.frame_92)
        self.frame_90.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_90.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_90.setObjectName("frame_90")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_90)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_90 = QtWidgets.QLabel(self.frame_90)
        self.label_90.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 11pt \"幼圆\";")
        self.label_90.setObjectName("label_90")
        self.horizontalLayout_6.addWidget(self.label_90)
        self.Logname = QtWidgets.QLineEdit(self.frame_90)
        self.Logname.setObjectName("Logname")
        self.horizontalLayout_6.addWidget(self.Logname)
        self.verticalLayout.addWidget(self.frame_90)
        self.frame_93 = QtWidgets.QFrame(self.frame_92)
        self.frame_93.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_93.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_93.setObjectName("frame_93")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_93)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_91 = QtWidgets.QLabel(self.frame_93)
        self.label_91.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 11pt \"幼圆\";")
        self.label_91.setObjectName("label_91")
        self.horizontalLayout_7.addWidget(self.label_91)
        self.logpass = QtWidgets.QLineEdit(self.frame_93)
        self.logpass.setObjectName("logpass")
        self.horizontalLayout_7.addWidget(self.logpass)
        self.verticalLayout.addWidget(self.frame_93)
        self.logBut = QtWidgets.QPushButton(self.frame_92)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.logBut.sizePolicy().hasHeightForWidth())
        self.logBut.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/Navigation/profile.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logBut.setIcon(icon)
        self.logBut.setObjectName("logBut")
        self.verticalLayout.addWidget(self.logBut)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_99.setText(_translate("Form", "      单位考勤打卡系统"))
        self.label_90.setText(_translate("Form", "姓名："))
        self.label_91.setText(_translate("Form", "密码："))
        self.logBut.setText(_translate("Form", "登录"))
