# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'staffWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(847, 592)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(30, 20, 141, 481))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(141, 431))
        self.frame.setStyleSheet("#frame{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.25, x2:1, y2:0.886364, stop:0.0681818 rgba(0, 196, 211, 255), stop:1 rgba(234, 125, 255, 255));\n"
"border-radius:20px;\n"
"}\n"
"QPushButton{\n"
"    border:none;\n"
"    font: 16pt \"幼圆\";\n"
"    color:rgb(255, 255, 255)\n"
"}\n"
"QPushButton:hover{\n"
"    padding-left:5px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 11pt \"幼圆\";")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pushButton_recognize = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_recognize.sizePolicy().hasHeightForWidth())
        self.pushButton_recognize.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../.designer/backup/Navigation/profile.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_recognize.setIcon(icon)
        self.pushButton_recognize.setObjectName("pushButton_recognize")
        self.verticalLayout.addWidget(self.pushButton_recognize)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pushButton_history = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pushButton_history.sizePolicy().hasHeightForWidth())
        self.pushButton_history.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../.designer/backup/Navigation/card.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_history.setIcon(icon1)
        self.pushButton_history.setObjectName("pushButton_history")
        self.verticalLayout.addWidget(self.pushButton_history)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(170, 40, 581, 441))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(581, 441))
        self.frame_2.setStyleSheet("#frame_2{\n"
"background-color:rgb(255, 255, 255);\n"
"border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(550, 0, 31, 31))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../.designer/backup/Navigation/multiply.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(20, 20))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 30, 561, 411))
        self.stackedWidget.setObjectName("stackedWidget")
        self.putin = QtWidgets.QWidget()
        self.putin.setObjectName("putin")
        self.stackedWidget.addWidget(self.putin)
        self.cognize = QtWidgets.QWidget()
        self.cognize.setObjectName("cognize")
        self.cognize_label = QtWidgets.QLabel(self.cognize)
        self.cognize_label.setGeometry(QtCore.QRect(30, 50, 481, 251))
        self.cognize_label.setText("")
        self.cognize_label.setObjectName("cognize_label")
        self.start_Button = QtWidgets.QPushButton(self.cognize)
        self.start_Button.setGeometry(QtCore.QRect(220, 320, 75, 23))
        self.start_Button.setObjectName("start_Button")
        self.stackedWidget.addWidget(self.cognize)
        self.datacon = QtWidgets.QWidget()
        self.datacon.setObjectName("datacon")
        self.stackedWidget.addWidget(self.datacon)
        self.history = QtWidgets.QWidget()
        self.history.setObjectName("history")
        self.search_table_2 = QtWidgets.QTableWidget(self.history)
        self.search_table_2.setGeometry(QtCore.QRect(10, 10, 541, 311))
        self.search_table_2.setObjectName("search_table_2")
        self.search_table_2.setColumnCount(0)
        self.search_table_2.setRowCount(0)
        self.view_all_2 = QtWidgets.QPushButton(self.history)
        self.view_all_2.setGeometry(QtCore.QRect(220, 350, 118, 23))
        self.view_all_2.setObjectName("view_all_2")
        self.stackedWidget.addWidget(self.history)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(520, 0, 31, 31))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"}\n"
"QPushButton:hover{\n"
"    padding-bottom:5px;\n"
"}")
        self.pushButton_6.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../.designer/backup/Navigation/minus.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon3)
        self.pushButton_6.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_6.setObjectName("pushButton_6")
        self.stackedWidget.raise_()
        self.pushButton_6.raise_()
        self.pushButton.raise_()

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "人脸识别门禁系统"))
        self.pushButton_recognize.setText(_translate("Form", "人脸识别"))
        self.pushButton_history.setText(_translate("Form", "识别记录"))
        self.start_Button.setText(_translate("Form", "识别打卡"))
        self.view_all_2.setText(_translate("Form", "浏览识别记录"))
